const fs = global.nodemodule["fs-extra"];
const moment = require("moment-timezone");

module.exports.config = {
  name: "Obot",
  version: "1.0.2",
  hasPermssion: 0,
  credits: "💫𝗔𝘁𝗶'𝗰𝗸-𝘃𝗮𝘂'𝘀❞💭𝗽𝗿𝗼𝗽𝗲𝗿𝘁𝘆🥀┼─🔐💜",
  description: "Goibot",
  commandCategory: "Noprefix",
  usages: "noprefix",
  cooldowns: 5,
};

module.exports.handleEvent = async function({ api, event, Users }) {
  const { threadID, senderID, body } = event;
  const name = await Users.getNameUser(senderID);

  // Current Dhaka Time
  const time = moment.tz("Asia/Dhaka").format("HH:mm:ss L");

  // Random replies
  const tl = [
    "শুনবো না😼তুমি আমাকে প্রেম করাই দাও নাই🥺পচা তুমি🥺",
    "এতো ডেকো না,প্রেম এ পরে যাবো🙈",
    "Bolo Babu, তুমি কি আমাকে ভালোবাসো? 🙈💋",
    "হ্যা বলো😒, তোমার জন্য কি করতে পারি😐😑?",
    "I love you janu🥰",
    "Bolo আমার জান ,কেমন আছো?😚 ",
    "Bot বলে অসম্মান Korcho,😰😿",
    "Hop beda😾,Boss Bolo boss😼",
    "চুপ Thako ,নাই তো Tomar দাত ভেগে দিবো কিন্তু",
    "Bot না , জানু বল জানু 😘",
    "আমাকে ডাকলে ,আমি কিন্তু কিস করে দিবো😘",
    "আমারে এতো Dakiyo না আমি মজা করার mood এ নাই এখন😒",
    "হ্যাঁ জানু , এইদিক এ আসো কিস দেই🤭😘",
    "কি হলো , মিস্টেক করচ্ছিস নাকি🤣",
    "বলো কি বলবা, সবার সামনে বলবা নাকি?🤭🤏",
    "হা বলো, শুনছি আমি 😏",
    "আর কত বার Dakbe ,শুনছি তো",
    "হুম বলো কি বলবে😒",
    "বলো কি করতে পারি তোমার জন্য",
    "আমি তো অন্ধ কিছু দেখি না🐸😎",
    "Bot না জানু,Bolo 😌",
    "বলো জানু 🌚",
    "হুম জান তোমার ওই খানে উম্মহ😑😘",
    "আহ শুনা আমার তোমার অলিতে গলিতে উম্মাহ😇😘",
    "jang hanga korba😒😬",
    "হুম জান তোমার অইখানে উম্মমাহ😷😘",
    "আসসালামু আলাইকুম বলেন আপনার জন্য কি করতে পারি..!🥰",
    "আমাকে এতো না ডেকে বস Atick কে একটা গফ দে 🙄",
    "🌻🌺💚-আসসালামু আলাইকুম ওয়া রাহমাতুল্লাহ-💚🌺🌻"
    // এখানে চাইলে আরও অনেক reply add করতে পারো
  ];

  const rand = tl[Math.floor(Math.random() * tl.length)];

  const lowerBody = body.toLowerCase();

  // Keyword Responses
  const keywordResponses = {
    "Miss you": "আমি তোমাকে রাইতে মিস খাই🥹🤖👅/👅-✘  🎀 🍒:))",
    "😘": "༊__🦋    -টুমার  রিস্কি রিস্কি চাউনিতে  হুইস্কির ফ্লেভার আছে"- 




 "উম্মাহ্-💋    ༊__🙈.🙆‍♀️🙆‍♀️🙆‍♀️",
    "help": "type /help",
    "Ki re": "-নাটক বুঝো আবেগ বুঝোনা.!🥲🤰",
    "Re": "-নাটক বুঝো আবেগ বুঝোনা.!🥲🤰",
    "ওই কিরে": "মধু মধু রসমালাই 🍆⛏️🐸🤣",
    "Oi kire": "মধু মধু রসমালাই 🍆⛏️🐸🤣",
    "...": "মধু মধু রসমালাই 🍆⛏️🐸🤣",
    "Bndopi": "তোর কোন কোন জায়গায় ব্যথা গো বান্ধবী ললিতা__🙂🐸🍆",
    "Dost": "তোর কোন কোন জায়গায় ব্যথা গো বান্ধবী ললিতা__🙂🐸🍆",
    "🫦": "কিরে হালা লুচ্চা, এগুলো কি ইমুজি দেস ।",
    "💋": "কিরে হালা লুচ্চা, এগুলো কি ইমুজি দেস ।",
    "Good morning": "GOOD MORNING দাত ব্রাশ করে খেয়ে নেও😚",
    "Gdm9": "GOOD MORNING দাত ব্রাশ করে খেয়ে নেও😚",
    "Atick": "উনি এখন কাজে বিজি আছে কি বলবেন আমাকে বলতে পারেন..!😘",
    "Owner": "ATICK",
    "Eeo": "ATICK",
    "Admin": "He is ATICK❤️ তাকে সবাই Atick নামে চিনে🤙",
    "Bot er baccha": "আমার বাচ্চা তো তোমার গার্লফ্রেন্ডের পেটে..!!🌚⛏️🌶️",
    "Kiss me": "️ তুমি পঁচা তোমাকে কিস দিবো না 🤭",
    "Tnx": "️এতো ধন্যবাদ না দিয়ে পারলে গার্লফ্রেন্ড টা দিয়ে DEO..!🌚⛏️🌶️",
    "ধন্যবাদ": "️এতো ধন্যবাদ না দিয়ে পারলে গার্লফ্রেন্ড টা দিয়ে দে..!🌚⛏️🌶️",
    "Thanks": "️এতো ধন্যবাদ না দিয়ে পারলে গার্লফ্রেন্ড টা দিয়ে দে..!🌚⛏️🌶️",
    "Name": "️MY NAME IS °_>𝗜𝘀𝗹𝗮𝗺𝗶𝗰𝗸 𝗰𝗵𝗮𝘁 𝗯𝗼𝘁",
    "Babu": "Hmmm Bolo-💋    ༊__🙈.🙆‍♀️🙆‍♀️🙆‍♀️",
    "হ্যালো": "ওই হ্যালো! 😎 কেমন আছো?",
    "Ki korcho": "আর কি, বসে বসে চা খাচ্ছি ☕😂",
    "Valo Acho": "হুম, Tmr সাথে কথা বলে ভালো লাগছে 😏",
    "Moja korcis": "মজা না করলে কি জীবন মজা লাগে? 😜",
    "Ki khubor": "খবর নাই, Tumi বল খবর কি? 😁",
    "Valo lagche": "আমারও ভালো লাগছে Tumar সাথে 😘",
    "Ki Solce": "চলছে তো আর কি, Tumi বল? 🤔",
    "Hea": "হ্যাঁ, ঠিক Bulco 😎",
    "Naa": "না না না! 🤨 কি বলছিস তুই?",
    "Suncis": "শুনছিই, কি Bolba? 👂",
    "Aso": "ঠিক আছে, আসছি 😏",
    "Jai": "চল, যাই! 🏃‍♂️💨",
    "সুপ্রভাত": "সুপ্রভাত! চা খেয়েছিস কি? ☕😎",
    "Sundor lagche": "ধন্যবাদ! তোর চোখও কম সুন্দর না 😏",
    "Voi payli": "ভয়? না না 😅 কি হলো?",
    "hasteco": "হাসছি 😂 তুই কি হাসছিস না?",
    "Mon kharap": "সব ঠিক হয়ে যাবে 😇",
    "Chup kor": "ঠিক আছে, চুপ 😶",
    "Kotha bolo": "বল কি হয়েছে 😎",
    "Valobashi": "ওই বাবা! 😍 আমারও ভালোবাসা তোর জন্য",
    "Valobashi na": "কি 😐? তাহলে কি করব আমি 😢",
    "Kemon ascis": "আমি ভালো, tumi বল কেমন Acho? 😎",
    "Kaj korcho": "হুম, একটু কাজ করছি 😅",
    "Ki khao": "হ্যা খাচ্ছি 😋 তুই কি খাস?",
    "Moja": "মজা তো সবসময় লাগবেই 😜",
    "Sotti": "সত্যি 😳 কি সত্যি বলছিস?",
    "Ascha": "ঠিক আছে 😎 চল, করা যাক",
    "Ok": "ওকে boss! 😉",
    "Hmm": "হুম 😌 বুঝলাম",
    "Ghum ase na": "_____ঘুম আসে না তাই ঘুমের মাইরে ষু/দি—!😿🐼",
    "Kotha bulcho na je": "বিরক্ত? 😳 না না, কি হয়েছে?",
    "ভালো লাগছে না": "কি হয়েছে? 😢",
    "খারাপ লাগছে": "হুম 😔 বল কি হয়েছে?",
    "Dhuke dilo": "🌻ঠাস করে ধরে, টুস করে ঢুকিয়ে দিলোহ্ উফফস্"—🥵👀🐸",
    "হুম ঠিক আছে": "ঠিক আছে 😎",
    "Abar": "আবার কি? 😏",
    "না হ্যাঁ": "না হ্যাঁ? কি বলছিস 😅",
    "Pom pom": "- আন্টি আপনার মাইয়া ব্রা ছাড়া রাস্তায় হাঁটে.....😊🤗☺️💋🤭পমপম দেখা যায়😋🙊💦🐸",
    "Nafij": "Nafij আমার -  সামনে- দিয়া- যাইস .!!☹️   !!নুনু ,! ভাইঙ্গা!! হাতে!! ধরাই!!দিমু!!😾🔨",
    "ধরা যাক": "ধরা যাক 😏",
    "চল": "চল 😎 কোথায় যাব?",
    "Magi": "যে মাগী ☺👅 সুখ পায়না স্বামীর খাটে 😑🖕সেই মাগী দুদু দেখায় টিকটকে🥵",
    "Baler bot": "সরি 😅 মাফ করে দাও",
    "Arohi": "__শীত করে ঝাং তোমার  ওই প্লাজুর নিচে একটু জায়গা  দিবা 😒<• 🥺💦🐸",
    "Atick abl": "প্রিয়ো আমার শহরে আসো কুওা দিয়ে ষুদাবো তুমাকে,🐰🐰",
    "Valo thak": "জানু পম পম খাবো 🥵💋",
    "Tui janis": "না না, কি হয়েছে 😢",
    "Vab nis": "ঠিক আছে, কোনো কথা নেই 😌",
    "হ্যালো": "ওই হ্যালো! 😎 কেমন আছো তুই?",
    "Kita Korcho": "আর কি, বসে বসে চা খাচ্ছি ☕😂",
    "Kew patta dee": "হুম, তোর সাথে কথা বলে ভালো লাগছে 😏",
    "Line marcho": "মজা না করলে কি জীবন মজা লাগে? 😜",
    "কী খবর": "খবর নাই, তুই বল খবর কি? 😁",
    "ভালো লাগছে": "আমারও ভালো লাগছে তোর সাথে 😘",
    "কি চলছে": "চলছে তো আর কি, তুই বল কি চলছে? 🤔",
    "হ্যাঁ": "হ্যাঁ, ঠিক বলেছিস 😎",
    "না": "না না না! 🤨 কি বলছিস তুই?",
    "শুনছিস": "শুনছিই, কি বলবি? 👂",
    "আসো": "ঠিক আছে, আসছি 😏",
    "যাই": "চল, যাই! 🏃‍♂️💨",
    "ধন্যবাদ": "এত ধন্যবাদ? 😳 বসে বসে হেসে ফেললাম 😆",
    "সুপ্রভাত": "সুপ্রভাত! চা খেয়েছিস কি? ☕😎",
    "সুন্দর লাগছে": "ধন্যবাদ! তোর চোখও কম সুন্দর না 😏",
    "ভয় পেয়েছিস": "ভয়? না না 😅 কি হলো?",
    "হাসো": "হাসছি 😂 তুই কি হাসছিস না?",
    "কেঁদো না": "কেন কেঁদো, সব ঠিক হয়ে যাবে 😇",
    "চুপ কর": "ঠিক আছে, চুপ 😶",
    "কথা বল": "ঠিক আছে, বল কি হয়েছে 😎",
    "ভালোবাসি": "ওই বাবা! 😍 আমারও ভালোবাসা তোর জন্য",
    "ভালোবাসি না": "কি 😐? তাহলে কি করব আমি 😢",
    "কেমন আছিস": "আমি ভালো, তুই বল কেমন আছিস? 😎",
    "কাজ করছ": "হুম, একটু কাজ করছি 😅",
    "খাও": "হ্যা খাচ্ছি 😋 তুই কি খাস?",
    "মজা": "মজা তো সবসময় লাগবেই 😜",
    "সত্যি": "সত্যি 😳 কি সত্যি বলছিস?",
    "না ভাই": "না ভাই! কি কিসের কথা বলছিস 😏",
    "ঠিক আছে": "ঠিক আছে 😎 চল, করা যাক",
    "ওকে": "ওকে boss! 😉",
    "হুম": "হুম 😌 বুঝলাম",
    "মনে পড়ছে": "মনে পড়ছে 😅 কি মনে পড়ল?",
    "বিরক্ত": "বিরক্ত? 😳 না না, কি হয়েছে?",
    "ভালো লাগছে না": "না না, কি হয়েছে? 😢",
    "খারাপ লাগছে": "হুম 😔 বল কি হয়েছে?",
    "হাসি": "হাসছি 😆 তুই হাসছিস না?",
    "হুম ঠিক আছে": "ঠিক আছে 😎 বুঝলাম",
    "আবার": "আবার কি? 😏",
    "না হ্যাঁ": "না হ্যাঁ? কি বলছিস 😅",
    "কি রে": "কি রে? 😎 বল",
    "কি খবর রে": "খবর কি রে? 😁",
    "ধরা যাক": "ধরা যাক 😏",
    "চল": "চল 😎 কোথায় যাব?",
    "ঠিক আছে boss": "ঠিক আছে boss! 😉",
    "সরি": "সরি 😅 মাফ করে দাও",
    "থিক আছে": "থিক আছে 😌 বুঝলাম",
    "শুয়েছি": "শুয়েছি? 😴 হুম",
    "ভালো থাক": "তুই ভালো থাক 😎",
    "সুন্দর লাগছে না": "না না, কি হয়েছে 😢",
    "কোনো কথা নেই": "ঠিক আছে, কোনো কথা নেই 😌",
    "বিরক্ত হচ্ছিস": "না না 😅 আর কি হয়েছে?",
    "হাহা": "হাহা 😆 তোর হাসি দারুন!",
    "দেখা হবে": "দেখা হবে 😏 কবে দেখা করব?",
    "সুন্দর": "ধন্যবাদ 😘 তোরও স্টাইল দারুন!",
    "মজা লাগছে": "মজা লাগছে? 😁 আমি ও মজা করছি!",
    "কেন": "কেন? 😳 কি হয়েছে বল",
    "ভাল": "ভাল? 😎 ঠিক আছে",
    "ভালো": "ভালো 😇 খুশি থাকো",
    "চিন্তা করো না": "চিন্তা নেই 😌 সব ঠিক হবে",
    "দেখতে চাই": "দেখতে চাই 😏 কি দেখাতে চাস?",
    "কথা দাও": "কথা দিচ্ছি 😎 ফিকির নাই",
    "হেল্প": "হেল্প? 😅 বল কি করতে পারি",
    "প্রশ্ন": "প্রশ্ন কর 😏 আমি উত্তর দিবো",
    "শোনো": "শোনছি 👂 কি বলছিস?",
    "হা": "হা 😆 ঠিক বলেছিস",
    "না না": "না না 😅 একদম ঠিক বলেছিস না",
    "বল": "বল 😎 কি বলতে চাস?",
    "শুরু": "শুরু কর 😏 আমি প্রস্তুত",
    "শেষ": "শেষ? 😢 আর কি বলব?",
    "Tumi kharap": "_ আমারে অশ্লীল কছ-! বাথরুমে গিয়া তো তুই ও ন্যাংটা হছ 😣⛏️",
    "hello": "Heyyy 😜 ki khobor?",
    "miss you": "Awww 😢 ami o tomake miss kortesi 🥹💔",
    "love you": "Oii 😘 tomake ami bhalobashi 🫶🔥",
    "fun": "Haha 😆 majaa kortesi, tumi ki aso?",
    "stop": "Oki 😅 thik ase, chup thakbo 😏",
    "what r u doing": "Bosh 😎 chill kortesi, tumi ki aso?",
    "good morning": "GM 😎 chaa khayechis naki? ☕",
    "bye": "Byee 😏 dekha hobe taratari! 🏃‍♂️",
    "lol": "Hahaha 😹 khub maja lagse naki?",
    "yess": "Oii 😎 perfect! ki plan?",
    "nooo": "Nooo 😱 really? 😳 ami chokh dhois na 😆",
    "kemon aso": "Besh 😎 tumi ki aso? 😏",
    "khobor": "Khobor bhalo 😌 tumi ki aso?",
    "hahaha": "Hahaha 😆 boro moja lagse naki?",
    "okay": "Oki 😎 thik ase bos",
    "awesome": "Wooo 😎 khub awesome 😏",
    "crazy": "Haha 😜 tumi total crazy 😹",
    "chill": "Chill 😎 bhalo ase, maja kor 😏",
    "funny": "Hahaha 😹 really funny 😆",
    "cute": "Aww 😍 khub cute 😘",
    "cool": "Oki 😎 cool vibe ase 😏",
    "good night": "GN 😴 sweet dreams 😌",
    "sleep": "Sleep 😴 bhalo ghum koro 😏",
    "wow": "Wooo 😱 amazing 😎",
    "huh": "Huh? 😳 ki boltes? 😆",
    "stoppp": "Oki 😅 chup thaklam 😏",
    "wait": "Wait 😌 ami aste asi 😎",
    "come": "Come 😏 kothae asbi? 🏃‍♂️",
    "go": "Go 😎 thik ase, dekha hobe 😏",
    "help": "Help 😅 ki lagse? 😳 bolo boss",
    "thanks": "Thanks 😎 no problem 😏",
    "sorry": "Sorry 😅 ami next time careful 😏",
    "haha": "Hahaha 😆 maja kor 😏",
    "fun time": "Fun time 😎 ready? 😏",
    "yooo": "Yooo 😎 ki khobor boss?",
    "bro": "Oii bro 😎 ki aso?",
    "sis": "Heyy sis 😏 ki khobor?",
    "friend": "Friend 😎 kemon aso? 😏",
    "love": "Love 😘 ami tomake bhalobashi 🫶",
    "okey": "Okey 😎 perfect 😏",
    "hmm": "Hmm 😌 bujhlam 😏",
    "yeah": "Yeah 😎 thik ase 😏",
    "nah": "Nah 😅 thik ase 😏",
    "mad": "Oii 😡 calm ho ja boss 😅",
    "excited": "Wooo 😎 ready for maja? 🤩",
    "hungry": "Oii 😋 khabar khayechis naki? 🍕",
    "sleepy": "Sleepy 😴 ghum ase naki? 🛌",
    "bored": "Bored 😒 kichu maja korte chai 😏",
    "confused": "Huh? 😳 ki bujhlam na 😅",
    "angry": "Oii 😡 shanti thako 😏",
    "love u": "Love u too 😘 tumi amar ❤️",
    "haha lol": "Hahaha 😹 maja lagse naki? 😏",
    "what's up": "Wassup 😎 ki khobor? 😏",
    "good evening": "GE 😎 evening shundor kor 😏",
    "good night boss": "GN 😴 shundor ghum koro 😏",
    "awesome bro": "Wooo 😎 truly awesome 😏",
    "funny sis": "Haha 😹 tumi funny 😏",
    "cool friend": "Cool 😎 chill korte thako 😏",
    "yummy": "Oii 😋 khub tasty 😏",
    "crazy bro": "Haha 😜 tumi total crazy 😹",
    "super": "Super 😎 amazing 😏",
    "ok bro": "Oki 😎 thik ase 😏",
    "let's go": "Let's go 😎 ready? 🏃‍♂️",
    "haha yes": "Hahaha 😆 perfect 😏",
    "no way": "No way 😱 really? 😳",
    "omg": "OMG 😱 ki boltes boss? 😏",
    "wowow": "Wooo 😎 amazing 😏",
    "hi": "Oii boss 😎 kemon aso? 😏",
    "hello": "Heyyy 😜 ki khobor?",
    "miss you": "Awww 😢 ami o tomake miss kortesi 🥹💔",
    "love you": "Oii 😘 tomake ami bhalobashi 🫶🔥",
    "fun": "Haha 😆 majaa kortesi, tumi ki aso?",
    "stop": "Oki 😅 thik ase, chup thakbo 😏",
    "what r u doing": "Bosh 😎 chill kortesi, tumi ki aso?",
    "good morning": "GM 😎 chaa khayechis naki? ☕",
    "bye": "Byee 😏 dekha hobe taratari! 🏃‍♂️",
    "lol": "Hahaha 😹 khub maja lagse naki?",
    "yess": "Oii 😎 perfect! ki plan?",
    "nooo": "Nooo 😱 really? 😳 ami chokh dhois na 😆",
    "kemon aso": "Besh 😎 tumi ki aso? 😏",
    "khobor": "Khobor bhalo 😌 tumi ki aso?",
    "hahaha": "Hahaha 😆 boro moja lagse naki?",
    "okay": "Oki 😎 thik ase bos",
    "awesome": "Wooo 😎 khub awesome 😏",
    "crazy": "Haha 😜 tumi total crazy 😹",
    "chill": "Chill 😎 bhalo ase, maja kor 😏",
    "funny": "Hahaha 😹 really funny 😆",
    "cute": "Aww 😍 khub cute 😘",
    "cool": "Oki 😎 cool vibe ase 😏",
    "good night": "GN 😴 sweet dreams 😌",
    "sleep": "Sleep 😴 bhalo ghum koro 😏",
    "wow": "Wooo 😱 amazing 😎",
    "huh": "Huh? 😳 ki boltes? 😆",
    "stoppp": "Oki 😅 chup thaklam 😏",
    "wait": "Wait 😌 ami aste asi 😎",
    "come": "Come 😏 kothae asbi? 🏃‍♂️",
    "go": "Go 😎 thik ase, dekha hobe 😏",
    "help": "Help 😅 ki lagse? 😳 bolo boss",
    "thanks": "Thanks 😎 no problem 😏",
    "sorry": "Sorry 😅 ami next time careful 😏",
    "haha": "Hahaha 😆 maja kor 😏",
    "fun time": "Fun time 😎 ready? 😏",
    "yooo": "Yooo 😎 ki khobor boss?",
    "bro": "Oii bro 😎 ki aso?",
    "sis": "Heyy sis 😏 ki khobor?",
    "friend": "Friend 😎 kemon aso? 😏",
    "love": "Love 😘 ami tomake bhalobashi 🫶",
    "okey": "Okey 😎 perfect 😏",
    "hmm": "Hmm 😌 bujhlam 😏",
    "yeah": "Yeah 😎 thik ase 😏",
    "nah": "Nah 😅 thik ase 😏",
    "mad": "Oii 😡 calm ho ja boss 😅",
    "excited": "Wooo 😎 ready for maja? 🤩",
    "hungry": "Oii 😋 khabar khayechis naki? 🍕",
    "sleepy": "Sleepy 😴 ghum ase naki? 🛌",
    "bored": "Bored 😒 kichu maja korte chai 😏",
    "confused": "Huh? 😳 ki bujhlam na 😅",
    "angry": "Oii 😡 shanti thako 😏",
    "love u": "Love u too 😘 tumi amar ❤️",
    "haha lol": "Hahaha 😹 maja lagse naki? 😏",
    "what's up": "Wassup 😎 ki khobor? 😏",
    "good evening": "GE 😎 evening shundor kor 😏",
    "good night boss": "GN 😴 shundor ghum koro 😏",
    "awesome bro": "Wooo 😎 truly awesome 😏",
    "funny sis": "Haha 😹 tumi funny 😏",
    "cool friend": "Cool 😎 chill korte thako 😏",
    "yummy": "Oii 😋 khub tasty 😏",
    "crazy bro": "Haha 😜 tumi total crazy 😹",
    "super": "Super 😎 amazing 😏",
    "ok bro": "Oki 😎 thik ase 😏",
    "let's go": "Let's go 😎 ready? 🏃‍♂️",
    "haha yes": "Hahaha 😆 perfect 😏",
    "no way": "No way 😱 really? 😳",
    "omg": "OMG 😱 ki boltes boss? 😏",
    "wowow": "Wooo 😎 amazing 😏",
    "sleep well": "Shundor ghum koro 😴 sweet dreams 💤",
    "boss": "Oii 😎 ki plan boss?",
    "lazy": "Haha 😅 ajke pura lazy mood 😏",
    "excuse": "Hmm 😏 excuse accept 😌",
    "surprise": "Wow 😱 ki surprise! 😎",
    "party": "Party time 😎 ready? 🥳",
    "game": "Game khelbi? 🎮 boss 😏",
    "music": "Music on 😎 mood bhalo kor 😏",
    "dance": "Dance korte chai? 💃🕺",
    "sing": "Sing korte chai? 🎤😎",
    "food": "Khub khub tasty 😋 ki khabo? 🍔",
    "coffee": "Coffee time ☕😏 chaa naki boss?",
    "tea": "Tea 🍵 boss mood chill 😎",
    "movie": "Movie dekhbo? 🍿😏",
    "tv": "TV time 😎 ki show?",
    "funny text": "Haha 😹 khub maja lagse naki? 😏",
    "cool stuff": "Cool 😎 total vibe 😏",
    "weather": "Weather bhalo 😏 ki plan boss?",
    "shopping": "Shopping korte jabo? 🛍️😎",
    "tired": "Tired 😴 boss rest nite hobe 😏",
    "happy": "Happy 😄 shundor din 😎",
    "sad": "Sad 😢 bos thik aso? 😏",
    "angry boss": "Oii 😡 shanti thako 😏",
    "fun day": "Fun day 😎 maja korte ready? 😏",
    "cute boss": "Aww 😍 boss khub cute 😏",
    "crazy vibe": "Haha 😜 totally crazy 😹",
    "super fun": "Super fun 😎 ready naki? 😏",
    "wow moment": "Wooo 😱 wow moment 😏",
    "omgg": "OMG 😱 really? 😳",
        "kemon aso": "Oii 😏 kemon aso boss, shundor din naki?",
    "ki korchish": "Besh 😎 busy naki, kisu maja kortesi?",
    "miss korchi": "Awww 🥹 ami o tomake miss kortesi boss 💔",
    "kotha bol": "Haa 😏 bolo, ami shunchi 🫶",
    "fun korte chai": "Haha 😆 ready boss? maja korte jabo!",
    "bored lagse": "Oii 😅 kichu maja korte hobe, idea ase?",
    "hahaha": "Hahaha 😹 total maja lagse naki?",
    "wow": "Wooo 😱 ki amazing, boss!",
    "chill korte chai": "Chill 😎 bhalo ase, mood thik ache?",
    "khawa dorkar": "Oii 😋 khabar khao naki? 🍔",
    "coffee time": "☕ Coffee ready boss? chaa naki?",
    "tea time": "🍵 Tea ready 😏 mood chill kor",
    "fun day": "Fun day 😎 ready naki maja korte?",
    "party korbo": "🥳 Party time! tumi ready naki?",
    "game khelbo": "🎮 Game ready boss? cholo start kori",
    "music suni": "🎵 Music on 😎 mood bhalo kor",
    "dance korte chai": "💃🕺 Dance korte ready naki?",
    "movie dekhbo": "🍿 Movie plan ase boss?",
    "sleep korte chai": "😴 Shundor ghum nite jabo naki?",
    "happy lagse": "😄 Bhalo lagse boss, smile kor!",
    "sad lagse": "😢 Boss, ki holo? bolo ami shunbo",
    "excited lagse": "🤩 Oii boss, ready naki maja korar jonno?",
    "lazy mood": "😅 Ajke pura lazy, kisu plan nai?",
    "cute boss": "😍 Boss khub cute lagse 😏",
    "funny moment": "😂 Hahaha maja lagse naki?",
    "tired lagse": "😴 Boss, rest nite hobe",
    "cool vibe": "😎 Total cool vibe ase boss",
    "omg ki": "OMG 😱 boss, really?",
    "wow moment": "Wooo 😱 ki wow moment!",
    "huh ki": "Huh? 😳 ki boltes boss?",
    "bhalo lagse": "☺️ Boss, shundor lage 😏",
    "kharap lagse": "😢 Kharap lagse naki boss?",
    "game plan": "🎮 Game ready? ami o join korbo",
    "party plan": "🥳 Party plan ase naki boss?",
    "fun time": "Haha 😆 ready naki boss maja korte?",
    "chill vibe": "😎 Chill boss, enjoy kor",
    "food time": "😋 Khabar ready? ami o asbo",
    "coffee break": "☕ Coffee break nibe boss?",
    "tea break": "🍵 Tea break time ase boss?",
    "music mood": "🎵 Music on 😎 mood bhalo kor",
    "dance mood": "💃🕺 Dance korte ready naki?",
    "sleep time": "😴 Ghum nite jabo boss?",
    "boss ki": "Oii 😎 ki plan boss?",
    "friend kemon": "Heyy 😏 friend ki aso?",
    "fun idea": "😂 Boss, idea ase maja korar?",
    "crazy mood": "Haha 😜 Total crazy boss 😹",
    "super mood": "😎 Super ready naki boss?",
    "amazing day": "😱 Wooo amazing day naki?",
    "excited mood": "🤩 Ready naki boss maja korar jonno?",
    "shundor din": "☺️ Shundor din boss, enjoy kor",
    "awesome vibe": "😎 Total awesome vibe ase boss",
    "wow wow": "😱 Wooo 😎 ki wow boss!",
    "hello boss": "Oii 😏 hello boss, kemon aso?",
    "hi friend": "Heyy 😎 friend ki aso?",
    "good morning": "GM 😎 chaa khayechis naki?",
    "good night": "GN 😴 Shundor ghum nite jabo?",
    "bye boss": "Byee 😏 dekha hobe taratari!",
    "see you": "Dekha hobe 😎 cholo kotha bolbo pore",
    "lol boss": "Hahaha 😹 khub maja lagse naki?",
    "funny boss": "😂 Boss, khub funny 😏",
    "love boss": "😘 Boss ami tomake bhalobashi 🫶",
    "crazy boss": "😜 Total crazy boss 😹",
    "awesome boss": "😎 Boss khub awesome 😏",
    "cool boss": "😎 Boss total cool vibe 😏",
    "happy boss": "😄 Boss, smile kor",
    "sad boss": "😢 Boss ki holo? bolo ami shunbo",
    "sleepy boss": "😴 Boss ghum lagse naki?",
    "hungry boss": "😋 Boss khabar khao naki?",
    "funny friend": "😂 Friend, khub maja lagse 😏",
    "cute friend": "😍 Friend khub cute 😏",
    "crazy friend": "😜 Friend total crazy 😹",
    "awesome friend": "😎 Friend khub awesome 😏",
    "cool friend": "😎 Friend cool vibe 😏",
    "happy friend": "😄 Friend khub smile 😏",
    "sad friend": "😢 Friend ki holo? bolo ami shunbo",
    "excited friend": "🤩 Friend ready naki maja korar jonno?",
    "fun idea friend": "😂 Friend, maja korar idea ase?",
    "chill friend": "😎 Friend chill vibe ase",
    "dance friend": "💃🕺 Friend ready dance korte?",
    "game friend": "🎮 Friend game ready?",
    "music friend": "🎵 Friend music on?",
    "movie friend": "🍿 Friend movie plan ase?",
    "coffee friend": "☕ Friend coffee ready naki?",
    "tea friend": "🍵 Friend tea ready naki?",
    "sleep friend": "😴 Friend ghum lagse naki?",
    "boss ready": "Oii 😎 Boss ready? maja korte?"
    "
  };

  // Check keywords
  for (let key in keywordResponses) {
    if (lowerBody === key) {
      return api.sendMessage(keywordResponses[key], threadID);
    }
  }

  // Random reply with /bot
  if (lowerBody.startsWith("/bot")) {
    return api.sendMessage(`${name}, ${rand}`, threadID);
  }
};

module.exports.run = function({ api, event, client, __GLOBAL }) { };
